### PR TITLE
Restore old syscall setresuid behavior when escalating/dropping privileges.

### LINKED ISSUE #1576: Instace started with --net as an unprivileged user in SUID mode is owned by root
### Version of Apptainer

`1.2.0-rc.2` in SUID mode on an x86-64 machine.

```Shell
$ apptainer --version
apptainer version 1.2.0-rc.2
```

### Expected behavior

After adding `$USER` to `allow net {users,groups}` in `apptainer.conf`(see below) and starting a `SIF` image with `apptainer instance start --net app.sif app_instance` as an unprivileged user, I expect it to be listed & controllable with e.g. `apptainer instance list`.

### Actual behavior

The started application _does not_ show up on `apptainer instance list`. It _does_ show up using `sudo apptainer instance list`. 
If launched with the `--net` flag, the Apptainer parent process is owned by `root` instead of `$USER`. 
If launched without the `--net` flag, the Apptainer parent process is owned by `$USER` and everything works fine.

### Steps to reproduce this behavior

When launching the instance without the `--net` flag, everything works as expected:

```Shell
$ apptainer instance start app.sif app
INFO:    instance started successfully

$ apptainer instance list
INSTANCE NAME    PID     IP    IMAGE
app              2894          /path/to/app.sif
```

As expected, the Apptainer parent process is owned by `$USER`:
```Shell
$ ps aux|grep Apptainer
pfriese     2893  0.0  0.1 1248240 18532 ?       Ssl  11:30   0:00 Apptainer instance: pfriese [app]
```

With the `--net` flag however, it does not:

```Shell
# with allow net {groups,networks} addition in apptainer.conf, see below
$ apptainer instance start --net app.sif app_instance
INFO:    instance started successfully

$ apptainer instance list
INSTANCE NAME    PID     IP    IMAGE
```

Crucially, the Apptainer parent process is now owned by `root`:

```Shell
$ ps aux|grep Apptainer
root        3334  0.0  0.1 1248240 21080 ?       Ssl  11:33   0:00 Apptainer instance: pfriese [app]
```

Listing the instances as `root` now reveals the previously started instance:

```
$ sudo apptainer instance list
INSTANCE NAME    PID     IP           IMAGE
app_instance     9757    10.22.0.4    /path/to/app.sif
```

#### Further Observation

Without the changes to `apptainer.conf` outlined below, the call `apptainer instance start --net app.sif app` fails with: 

```Shell
# without allow net {users,groups,networks} addition in apptainer.conf
% apptainer instance start --net app.sif app
ERROR:   Network bridge is not permitted for unprivileged users.
ERROR:   container cleanup failed: no instance found with name app
FATAL:   container creation failed: network requires root or a suid installation with /etc/subuid --fakeroot; non-root users can only use --network=none unless permitted by the administrator

FATAL:   while executing starter: failed to start instance: while running /usr/local/libexec/apptainer/bin/starter-suid: exit status 255
```

Curiously, _without_ the `allow net {users,groups,networks}` settings, the call `apptainer instance start --net --fakeroot app.sif app`, as recommended by the error message above, succeeds with:

```Shell
# without allow net {users,groups,networks} addition in apptainer.conf, with /etc/sub{uid,gid} entries
% apptainer instance start --net --fakeroot app.sif app
INFO:    gocryptfs not found, will not be able to use gocryptfs
WARNING: Only --network=fakeroot is permitted in --fakeroot mode. You requested 'bridge'.
WARNING: Overriding with --network=fakeroot
INFO:    underlay of /etc/localtime required more than 50 (87) bind mounts
WARNING: Could not get ipv4 no IP found for network bridge
WARNING: Could not get ipv6 no IP found for network bridge
WARNING: Could not get ip for root: could not get ip

INFO:    instance started successfully
```

_The same behaviour regarding ownership by `root` is observed:_
```Shell
% apptainer instance list
INSTANCE NAME    PID    IP    IMAGE

% sudo apptainer instance list             
INSTANCE NAME    PID     IP    IMAGE
app              6195          /path/to/app.sif

% ps aux|grep Apptainer
root        7368  0.6  0.1 1174508 20340 ?       Ssl  12:00   0:00 Apptainer instance: pfriese [app]
```

##### apptainer.conf

During installation, the Apptainer configuration file at `/usr/local/etc/apptainer/apptainer.conf` was extended with the following settings:

```
allow net users = pfriese
allow net groups = pfriese
allow net networks = bridge
```

The user/group `pfriese` belongs to the invoking `$USER` in the examples above.

##### subuid/subgid

The files `/etc/subuid` and `/etc/subgid` contain the following line:

```
pfriese:100000:65536
```

#### Apptainer definition file

```sif
Bootstrap: docker
From: archlinux:base-devel-20230709.0.163418

%post
    pacman --noconfirm --noprogressbar -Suyq
```

### What OS/distro are you running

ArchLinux with kernel `6.4.4-arch1-1`

```
Linux $hostname 6.4.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 19 Jul 2023 19:19:38 +0000 x86_64 GNU/Linux
```

### How did you install Apptainer

Installed from source on tag `v1.2.0-rc.2` (via `git clone` & `git branch`) and with `mconfig --with-suid`.
In addition, the `squashfuse_ll` addition was installed from source on version 0.2.0.

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Restore old syscall setresuid behavior when escalating/dropping privileges to only change UID for the locked thread

### This fixes or addresses the following GitHub issues:

 - Fixes #1576 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/pkg/util/priv/priv_linux.go [hunk 1]
```diff
@@ -16,19 +16,23 @@ import (
 )
 
 // Escalate escalates privileges of the thread or process.
-// Since Go 1.16 syscall.Setresuid is an all-thread operation.
-// A runtime.LockOSThread operation remains for older versions of Go.
+// Since Go 1.16 syscall.Setresuid is an all-thread operation,
+// keep calling syscall directly restore old behavior to change
+// UID for the locked thread only.
```
Comment (DrDaveD) [inline internal/pkg/util/priv/priv_linux.go:21]: I find this comment confusing.  I suggest 
```
// keep calling syscall directly to restore the old behavior of changing
// the UID for the locked thread only.
```
and likewise again below.

**Review by DrDaveD — CHANGES_REQUESTED** [review]

**Comment by DrDaveD** [comment]
Also this will need a CHANGELOG entry (just above the v1.2.0 release, not part of the other changes listed above there now which are for 1.3)

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
It looks like Sylabs did much the same thing in a slightly different way for a different purpose later in sylabs/singularity#3444.
