### PR TITLE
disable cgroup when hidepid mount flag is set

### LINKED ISSUE #1779: Incompatibility between cgroups v2 and hidepid
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.2.4-1.el9
```

### Expected behavior

This command should be successful:
```
apptainer instance start docker://centos:7 tstins
```

### Actual behavior

The command fails and the following error message is displayed:
```
INFO:    Using cached SIF image
ERROR:   container cleanup failed: no instance found with name tstins
FATAL:   container creation failed: while applying cgroups config: while creating cgroup manager: failed to connect to dbus (hint: for rootless containers, maybe you need to install dbus-user-session package, see https://github.com/opencontainers/runc/blob/master/docs/cgroup-v2.md): could not execute `busctl --user --no-pager status` (output: "Failed to get credentials: Operation not permitted\nBusAddress=unix:path=/run/user/51171/bus\nBusScope=user\nBusID=9427da0aa93b547eb91b7c5ce1c2ca11\n"): exit status 1

FATAL:   while executing starter: failed to start instance: while running /usr/libexec/apptainer/bin/starter: exit status 255
```

### Steps to reproduce this behavior

Run the above command on RHEL9 with hidepid enabled (for example, by `sudo mount /proc -o remount,hidepid=1`).

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### How did you install Apptainer

```
$ rpm -qa | grep apptainer
apptainer-1.2.4-1.el9.x86_64
```

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

disable cgroup when `hidepid` mount flag is set.

### This fixes or addresses the following GitHub issues:

 - Fixes #1779

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: internal/pkg/runtime/launch/launcher_linux.go [hunk 1]
```diff
@@ -1074,6 +1075,11 @@ func (l *Launcher) setCgroups(instanceName string) error {
 		return nil
 	}
 
+	if hidePid {
+		sylog.Debugf("Instance stats will not be available because of hidePid is set")
```
Comment (DrDaveD) [inline internal/pkg/runtime/launch/launcher_linux.go:1079]: Instead of `hidePid is set` use `hidepid option is set on /proc mount`

File: CHANGELOG.md [hunk 2]
```diff
@@ -60,6 +60,8 @@ For older changes see the [archived Singularity change log](https://github.com/a
 ## Changes for v1.2.x
 
 - Disable the usage of cgroup in instance creation when `--fakeroot` is passed.
+- Disable the usage of cgroup in instance creation when `hidepid` mount option
+  is set.
```
Comment (DrDaveD) [inline CHANGELOG.md:64]: Add `on /proc`.

**Review by DrDaveD — CHANGES_REQUESTED** [review]

File: internal/pkg/runtime/launch/launcher_linux.go (hunk 1 above)
Comment (JasonYangShadow) [reply internal/pkg/runtime/launch/launcher_linux.go]: thanks! updated.

File: CHANGELOG.md (hunk 2 above)
Comment (JasonYangShadow) [reply CHANGELOG.md]: thanks! updated.

**Review by DrDaveD — APPROVED** [review]

**Comment by DrDaveD** [comment]
Please also cherry-pick to release-1.2 branch.
