### PR TITLE
disable cgroup when --fakeroot is used in instance start

### LINKED ISSUE #1749: instance start failed with --fakeroot
### Version of Apptainer

What version of Apptainer (or Singularity) are you using?
$ apptainer --version
apptainer version 1.2.2-1.el7

### Expected behavior

What did you expect to see when you do...?
instance should start with --fakeroot

### Actual behavior

What actually happened? Why was it incorrect?

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

$ apptainer instance start --fakeroot docker://alpine a1
INFO:    Using cached SIF image
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    Using cached SIF image
INFO:    Using fakeroot command combined with root-mapped namespace
ERROR:   container cleanup failed: no instance found with name a1
FATAL:   container creation failed: while applying cgroups config: Interactive authentication required.

FATAL:   while executing starter: failed to start instance: while running /usr/libexec/apptainer/bin/starter: exit status 255

### What OS/distro are you running

$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### How did you install Apptainer

RPM

$ rpm -qa|egrep apptainer
apptainer-1.2.2-1.el7.x86_64

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

Aligning the behavior of `apptaienr instance start --fakeroot` on cgroup v1 &v2. 
Disable the cgroup usage on cgroup v2 when `--fakeroot` is passed as well.

### This fixes or addresses the following GitHub issues:

 - Fixes #1749 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

### Test
```
vagrant@ubuntu:~/test$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
vagrant@ubuntu:~/test$ apptainer version
1.2.0-rc.1+457-g1f2bce9ac
vagrant@ubuntu:~/test$ apptainer instance start --fakeroot alpine.sif a1
INFO:    instance started successfully
vagrant@ubuntu:~/test$ apptainer instance list
INSTANCE NAME    PID       IP    IMAGE
a1               282416          /home/vagrant/test/alpine.sif
vagrant@ubuntu:~/test$ apptainer instance stop a1
INFO:    Stopping a1 instance of /home/vagrant/test/alpine.sif (PID=282416)
vagrant@ubuntu:~/test$ 
```

### CODE REVIEW

File: internal/pkg/runtime/launch/launcher_linux.go [hunk 1]
```diff
@@ -1069,6 +1069,11 @@ func (l *Launcher) setCgroups(instanceName string) error {
 		return nil
 	}
 
+	if l.cfg.Fakeroot {
+		sylog.Debugf("Instance starts without the usage of cgroup as fakeroot flag is passed.")
```
Comment (DrDaveD) [inline internal/pkg/runtime/launch/launcher_linux.go:1073]: That's a confusing message.  Make it
```
Instance stats will not be available because of fakeroot mode
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -59,6 +59,10 @@ For older changes see the [archived Singularity change log](https://github.com/a
 
 ## Changes for v1.2.x
 
+### Bug Fixes
+
```
Comment (DrDaveD) [inline CHANGELOG.md:63]: Leave out this extra header because we don't distinguish types of updates in patch releases.

**Review by DrDaveD — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 2 above)
Comment (JasonYangShadow) [reply CHANGELOG.md]: thanks! reflected in the latest commit

File: internal/pkg/runtime/launch/launcher_linux.go (hunk 1 above)
Comment (JasonYangShadow) [reply internal/pkg/runtime/launch/launcher_linux.go]: thanks! reflected in the latest commit

File: internal/pkg/runtime/launch/launcher_linux.go [hunk 3]
```diff
@@ -1050,7 +1050,7 @@ func (l *Launcher) setCgroups(instanceName string) error {
 	// root can always create a cgroup.
 	useCG := l.uid == 0
 	// non-root needs cgroups v2 unified mode + systemd as cgroups manager.
-	if l.uid != 0 && lccgroups.IsCgroup2UnifiedMode() && l.engineConfig.File.SystemdCgroups {
+	if l.uid != 0 && lccgroups.IsCgroup2UnifiedMode() && l.engineConfig.File.SystemdCgroups && !l.cfg.Fakeroot {
```
[the remark this answers is not in the document]
Comment (JasonYangShadow) [reply internal/pkg/runtime/launch/launcher_linux.go]: thanks! reflected in the latest commit

**Comment by DrDaveD** [comment]
Please also cherry-pick to the release-1.2 branch.
