### PR TITLE
Fix the issue that APPTAINER_MESSAGELEVEL does not have effect

### LINKED ISSUE #1556: APPTAINER_MESSAGELEVEL doesn't have much effect
At least on the main branch, there's an APPPTAINER_MESSAGELEVEL environment variable referenced in pkg/sylog/sylog.go but setting the variable does not have much effect. Reproduce by setting `APPTAINER_MESSAGELEVEL=5` which should put it into debug mode.  A couple of debug messages come out, and then it stops.

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

This `APPTAINER_MESSAGELEVEL` is only used when sylog is initialized, so we need to do some calculation between log level envs and message level env. 
https://github.com/JasonYangShadow/apptainer/blob/issue%2F1556/cmd/internal/cli/apptainer.go#L275
https://github.com/JasonYangShadow/apptainer/blob/issue%2F1556/cmd/internal/cli/apptainer.go#L291

### This fixes or addresses the following GitHub issues:

 - Fixes #1556 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

File: cmd/internal/cli/apptainer.go [hunk 1]
```diff
@@ -282,7 +288,7 @@ func setSylogMessageLevel() {
 	} else if silent {
 		level = -3
 	} else {
-		level = 1
+		level = sylog.Max(level, 1)
```
Comment (DrDaveD) [inline cmd/internal/cli/apptainer.go:291]: Use `math.Max()` instead and delete the new function below.

File: pkg/sylog/sylog.go [hunk 2]
```diff
@@ -20,7 +20,7 @@ import (
 	"strings"
 )
 
-const messageLevelEnv = "APPTAINER_MESSAGELEVEL"
+const MessageLevelEnv = "APPTAINER_MESSAGELEVEL"
```
Comment (DrDaveD) [inline pkg/sylog/sylog.go:23]: Instead of making this global, I think it would be better to have a function to get the message level.

In fact, for almost all environment variables we support either a SINGULARITY_ or APPTAINER_ prefix.  If it's not difficult to use the common function where that's done that would be better, even though I know it wasn't being done before.  For the test case where this variable is set I think it's fine to use the string `APPTAINER_MESSAGELEVEL` rather than a global variable name.

**Review by DrDaveD — CHANGES_REQUESTED** [review]
Don't forget a CHANGELOG entry.  This is a bug fix so it will be backported to release-1.2.  That means there should be a new `Changes since last release` section just above the v1.2.0 release, it shouldn't join all the existing changes in the CHANGELOG main branch which are for 1.3.

**Comment by JasonYangShadow** [comment]
@DrDaveD 
hmm, find something that is a bit of inconsistency. 
here, we are setting both `APPTAINER_MESSAGELEVEL` and `--slient`

Though it is reasonable because until setSylogMessageLevel is called, the message level is changed. So any debug messages outside of that will be printed out. 

```
vagrant@ubuntu:~/test$ apptainer --silent build --force 1.sif docker://alpine:latest
DEBUG   [U=1000,P=63024]   func1()                       Install prefix is /usr/local
DEBUG   [U=1000,P=63024]   func1()                       Using apptainer directory "/home/vagrant/.apptainer"
DEBUG   [U=1000,P=63101]   func1()                       Install prefix is /usr/local
DEBUG   [U=1000,P=63101]   func1()                       Using apptainer directory "/home/vagrant/.apptainer"
DEBUG   [U=1000,P=63101]   setValue()                    Updated flag 'silent' value to: true
vagrant@ubuntu:~/test$ echo $APPTAINER_MESSAGELEVEL
5
```

File: cmd/internal/cli/apptainer.go (hunk 1 above)
Comment (JasonYangShadow) [reply cmd/internal/cli/apptainer.go]: thanks! reflected in this commit
https://github.com/apptainer/apptainer/pull/1569/commits/1a2003474ceaa5144f602b234aa4bd811f3d336b

File: pkg/sylog/sylog.go (hunk 2 above)
Comment (JasonYangShadow) [reply pkg/sylog/sylog.go]: just using pure string instead
https://github.com/apptainer/apptainer/pull/1569/commits/1a2003474ceaa5144f602b234aa4bd811f3d336b

Comment (DrDaveD) [reply pkg/sylog/sylog.go]: How about using nternal/pkg/util/env/env.go's GetenvLegacy to get the MESSAGELEVEL?

**Comment by DrDaveD** [comment]
> @DrDaveD hmm, find something that is a bit of inconsistency. here, we are setting both `APPTAINER_MESSAGELEVEL` and `--slient`

I don't think we really need to worry about the case of somebody using inconsistent options.

File: pkg/sylog/sylog.go (hunk 2 above)
Comment (JasonYangShadow) [reply pkg/sylog/sylog.go]: reflected in this commit
https://github.com/apptainer/apptainer/pull/1569/commits/7f8566c352d1a5affa0cfdbef11bc61a0c9130b6
sylog/sylog_dummy could not use GetenvLegacy due to the cycle import.

File: CHANGELOG.md [hunk 3]
```diff
@@ -27,6 +27,12 @@ For older changes see the [archived Singularity change log](https://github.com/a
   pkg/build/types/parser.All(), `.Raw` contains the raw content of a single
   build stage. Otherwise, it is equal to `.FullRaw`.
 
+## Changes since last release
+
+### Bug fixes
+
+- Fix the issue that `APPTAINER_MESSAGELEVEL` does not have effect.
```
Comment (DrDaveD) [inline CHANGELOG.md:34]: Please change to
```
- Fix `$APPTAINER_MESSAGELEVEL` to correctly set the logging level.
```

**Review by DrDaveD — CHANGES_REQUESTED** [review]

File: pkg/sylog/sylog_dummy.go [hunk 4]
```diff
@@ -14,13 +14,23 @@ package sylog
 import (
 	"io"
 	"os"
+	"strconv"
 )
 
+const messageLevelEnv = "APPTAINER_MESSAGELEVEL"
```
[the remark this answers is not in the document]
Comment (JasonYangShadow) [reply pkg/sylog/sylog_dummy.go]: thanks for the comment! fixed in this commit
https://github.com/apptainer/apptainer/pull/1569/commits/04ffbdbffa3c88229578e5befccb5b62be3198d0

File: CHANGELOG.md (hunk 3 above)
Comment (JasonYangShadow) [reply CHANGELOG.md]: thanks for the comment! fixed in this commit
https://github.com/apptainer/apptainer/pull/1569/commits/04ffbdbffa3c88229578e5befccb5b62be3198d0

**Review by DrDaveD — APPROVED** [review]
