### PR TITLE
Loop device fix

### LINKED ISSUE #115: make loop device more reliable
need for apptainer 1.0.0

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Sleep retry logic was restored to 5 retries and a sleep interval of 200ms.
Additionally after this period of 1s we proceed with a cache flush:
- `BLKFLSBUF` ioctl command is issued for image file located on a block device
- or by calling `sync` syscall

And after that if we keep seeing `EAGAIN` error, a grace period of one second is added before returning an error.

To reduce lock contention introduce by all those sleeping periods, the global lock on `/dev` was removed, instead an exclusive lock is associated to a single loop device only when shared loop devices is enabled.

- Fixes #115

### CODE REVIEW

**Review by PaulCharlton — APPROVED** [review]

File: pkg/util/loop/loop.go [hunk 1]
```diff
@@ -122,29 +128,25 @@ func (loop *Device) AttachFromFile(image *os.File, mode int, number *int) error
...
 
 		// Try to open an existing loop device, but don't create a new one
-		loopFd, err := openLoopDev(device, mode, false)
+		loopFd, releaseLock, err := openLoopDev(device, mode, false, true)
 		if err != nil {
 			if !os.IsNotExist(err) {
-				sylog.Debugf("Couldn't open loop device %d: %v\n", device, err)
+				sylog.Debugf("Couldn't open loop device %d: %s\n", device, err)
 			}
 			continue
```
Comment (PaulCharlton) [inline pkg/util/loop/loop.go:145]: @cclerget are release lock and err guaranteed to be mutually exclusive?

File: pkg/util/loop/loop.go [hunk 2]
```diff
@@ -154,8 +156,7 @@ func (loop *Device) shareLoop(imageIno, imageDev uint64, mode int, number *int)
 			// be sure that the loop device won't be released between this
 			// check and the mount of the filesystem
 			sylog.Debugf("Sharing loop device %d", device)
-			loop.fd = new(int)
-			*loop.fd = loopFd
+			loop.fd = &loopFd
```
Comment (PaulCharlton) [inline pkg/util/loop/loop.go:159]: @cclerget loop.fd is not thread-safe, and not protected here.

File: pkg/util/loop/loop.go [hunk 3]
```diff
@@ -168,82 +169,48 @@ func (loop *Device) shareLoop(imageIno, imageDev uint64, mode int, number *int)
...
-		clearDevice := false
 
 		// Try to open the loop device, creating the device node if needed
-		loopFd, err := openLoopDev(device, mode, true)
+		loopFd, releaseLock, err := openLoopDev(device, mode, true, loop.Shared)
 		if err != nil {
-			sylog.Debugf("couldn't openLoopDev loop device %d: %v", device, err)
+			sylog.Debugf("Couldn't open loop device %d: %v", device, err)
 			return err
 		}
```
Comment (PaulCharlton) [inline pkg/util/loop/loop.go:191]: @cclerget what about `defer releaseDevice...`

File: pkg/util/loop/loop.go [hunk 4]
```diff
@@ -253,39 +220,157 @@ func (loop *Device) attachLoop(image *os.File, mode int, number *int) error {
...
+			continue
+		}
+		// trigger block device flush command
+		f, err := os.Open(e.Source)
+		if err != nil {
+			return fmt.Errorf("while opening %s: %s", e.Source, err)
+		}
+		defer f.Close()
+
+		_, _, esys := syscall.Syscall(syscall.SYS_IOCTL, f.Fd(), unix.BLKFLSBUF, 0)
```
Comment (PaulCharlton) [inline pkg/util/loop/loop.go:364]: @cclerget something to consider ... bd_flush may not flush at the FS level, nor stop FS I/o in flight.   Noting that loop device is rare use-case where kernel internally actually captures an FD.    Seems like there should be some ioctl at the mount point which performs fs.flush properly

File: pkg/util/loop/loop.go (hunk 1 above)
Comment (cclerget) [reply pkg/util/loop/loop.go:145]: releaseLock is valid only if the loop device was opened successfully

File: pkg/util/loop/loop.go (hunk 2 above)
Comment (cclerget) [reply pkg/util/loop/loop.go:159]: `loop` is a short-live object not a singleton object and `AttachFromFile` is not intended to be called in parallel for the same instance

File: pkg/util/loop/loop.go (hunk 3 above)
Comment (cclerget) [reply pkg/util/loop/loop.go:191]: stacking defer inside loop is not ideal here as it would lead to side effects like hitting the file descriptor limit

File: pkg/util/loop/loop.go (hunk 4 above)
Comment (cclerget) [reply pkg/util/loop/loop.go:364]: I didn't find more granular than this call available from user space, this is called after the sleep period of 1s, so we are already in a worst case scenario, this is not 100% reliable and it's provided as best-effort, but as 5.8 kernel introduced `LOOP_CONFIGURE` ioctl allowing to set the file descriptor and the offset/sizelimit in a single ioctl command, this issue would disappear. I won't push other effort on fixing this one, I restored the old sleeping behavior and added some flushing helper, I'm done

File: .github/workflows/ci.yml [hunk 5]
```diff
@@ -209,6 +209,13 @@ jobs:
           E2E_PARALLEL: 8
         run: make -C ./builddir e2e-test
 
+      - name: Loop device debug
```
Comment (ikaneshiro) [inline .github/workflows/ci.yml:212]: Lets remove this before merging

**Review by ikaneshiro — APPROVED** [review]
lgtm
