### PR TITLE
Suppress unneeded warnings and pass message level value to post script instance

### LINKED ISSUE #1314: Nvidia GPU not visible in post script
### Version of Apptainer

`apptainer version 1.1.8-1`

### Expected behavior

The build should succeed and the GPU should be visible while the post script is executed.

### Actual behavior

The build fails with the message

```sh
INFO:    Running post scriptlet
+ nvidia-smi
/.post.script: 1: /.post.script: nvidia-smi: not found
FATAL:   While performing build: while running engine: exit status 127
```

When the post script is commented out, the build succeeds and the container runs fine (i.e. `nvidia-smi` is correctly recognized in the test and run scripts).

<details><summary>Output of build without post script</summary>

```sh
INFO:    Adding runscript
INFO:    Adding testscript
INFO:    Running testscript
Wed May  3 11:23:40 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 00000000:8A:00.0 Off |                    0 |
| N/A   36C    P0    31W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
INFO:    Creating SIF file...
INFO:    Build complete: test.sif
```

</details>
<details><summary>Output of running the image</summary>

```sh
INFO:    underlay of /etc/localtime required more than 50 (66) bind mounts
INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (198) bind mounts
Wed May  3 11:30:32 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 00000000:8A:00.0 Off |                    0 |
| N/A   37C    P0    31W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

</details>

### Steps to reproduce this behavior

Using following definition file (`test.def`)

```
Bootstrap: docker
From: ubuntu:18.04

%post
    nvidia-smi

%test
    nvidia-smi

%runscript
    nvidia-smi
```

and using the commands `apptainer build --nv test.sif test.def` for building (fails unless the post section is commented out) and `apptainer run --nv test.sif` for running the image.

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Apptainer

Not sure, this is a shared HPC environment. I asked the administrators for further details and support but was wondering if something else could be causing this behavior.

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

Suppress unneeded warnings and pass message level value to post script instance

### This fixes or addresses the following GitHub issues:

 - Fixes #1314

#### Before submitting a PR, make sure you have done the following:

- [ ] Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] Make sure all commits are signed-off with `git commit -s`, see the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [ ] Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md), if necessary according to the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [ ] Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)).
- [ ] Based this PR against the appropriate branch according to the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md).

### Test

```
[vagrant@localhost test]$ cat nvidia.def 
Bootstrap: docker
From: ubuntu:18.04

%test
    nvidia-smi

%runscript
    nvidia-smi

%post
    nvidia-sm

[vagrant@localhost test]$ apptainer build nvidia.sif nvidia.def
INFO:    Starting build...
INFO:    Fetching OCI image...
24.5MiB / 24.5MiB [===================================================================] 100 % 0.0 b/s 0s
INFO:    Extracting OCI image...
INFO:    Inserting Apptainer configuration...
INFO:    Running post scriptlet
+ nvidia-smi
/.post.script: 1: /.post.script: nvidia-smi: not found
FATAL:   While performing build: while running engine: while running %post section: exit status 127

[vagrant@localhost test]$ apptainer build --nv nvidia.sif nvidia.def
INFO:    Starting build...
INFO:    Fetching OCI image...
24.5MiB / 24.5MiB [===================================================================] 100 % 0.0 b/s 0s
INFO:    Extracting OCI image...
INFO:    Inserting Apptainer configuration...
INFO:    Running post scriptlet
WARNING: Could not find any nv files on this host!
+ nvidia-smi
/.post.script: 1: /.post.script: nvidia-smi: not found
FATAL:   While performing build: while running engine: while running %post section: exit status 127

[vagrant@localhost test]$ apptainer -s build --nv nvidia.sif nvidia.def
+ nvidia-smi
/.post.script: 1: /.post.script: nvidia-smi: not found
FATAL:   While performing build: while running engine: while running %post section: exit status 127

[vagrant@localhost test]$ apptainer -q build --nv nvidia.sif nvidia.def
WARNING: Could not find any nv files on this host!
+ nvidia-smi
/.post.script: 1: /.post.script: nvidia-smi: not found
FATAL:   While performing build: while running engine: while running %post section: exit status 127

[vagrant@localhost test]$ apptainer build --ignore-subuid --nv nvidia.sif nvidia.def
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under the fakeroot command
INFO:    Starting build...
INFO:    Fetching OCI image...
24.5MiB / 24.5MiB [====================================================================] 100 % 0.0 b/s 0s
INFO:    Extracting OCI image...
INFO:    Inserting Apptainer configuration...
INFO:    Running post scriptlet
WARNING: Could not find any nv files on this host!
FATAL:   exec /.singularity.d/libs/fakeroot failed: a shared library is likely missing in the image
INFO:    If error was from fakeroot, try --ignore-fakeroot-command and
INFO:      maybe use fakeroot inside the %post section as described at
INFO:      https://apptainer.org/docs/user/latest/fakeroot.html#fakeroot-inside-def
FATAL:   While performing build: while running engine: while running %post section: exit status 255

[vagrant@localhost test]$ apptainer -q build --ignore-subuid --nv nvidia.sif nvidia.def
WARNING: Could not find any nv files on this host!
FATAL:   exec /.singularity.d/libs/fakeroot failed: a shared library is likely missing in the image
FATAL:   While performing build: while running engine: while running %post section: exit status 255

[vagrant@localhost test]$ apptainer -s build --ignore-subuid --nv nvidia.sif nvidia.def
FATAL:   exec /.singularity.d/libs/fakeroot failed: a shared library is likely missing in the image
FATAL:   While performing build: while running engine: while running %post section: exit status 255
```

### CODE REVIEW

**Comment by JasonYangShadow** [comment]
@DrDaveD 
Not sure if the PR meets our needs, I think we can pass `APPTAINER_MESSAGELEVEL` to sub-instance (post script spawn one), so that we can control the sub-instance as well?

File: internal/pkg/runtime/engine/apptainer/container_linux.go [hunk 1]
```diff
@@ -2351,7 +2351,7 @@ func (c *container) createCwdDir(system *mount.System) error {
 	cwdHost := filepath.Clean(c.engine.EngineConfig.GetCwd())
 	if cwdHost == "" || cwdHost == "/" {
 		c.skipCwd = true
-		sylog.Warningf("No current working directory set: skipping mount")
+		sylog.Debugf("No current working directory set: skipping mount")
```
Comment (DrDaveD) [inline internal/pkg/runtime/engine/apptainer/container_linux.go:2354]: I'm not sure it's a good idea to change all these messages to debug level.

The nested apptainer is invoked with `--pwd /` so I'm pretty sure it's only the second case that we care about.  How about it stays as a warning if `cwdHost == ""` but doesn't print anything if `cwdHost == "/"`.

File: internal/pkg/runtime/engine/apptainer/container_linux.go [hunk 2]
```diff
@@ -2278,7 +2278,7 @@ func (c *container) addCwdMount(system *mount.System) error {
 
 	cwdHost := filepath.Clean(c.engine.EngineConfig.GetCwd())
 	if cwdHost == "" {
-		sylog.Warningf("No current working directory set: skipping mount")
+		sylog.Debugf("No current working directory set: skipping mount")
```
Comment (DrDaveD) [inline internal/pkg/runtime/engine/apptainer/container_linux.go:2281]: Are you sure this is actually relevant?  I'd rather keep it as a warning.

File: internal/pkg/build/stage.go [hunk 3]
```diff
@@ -83,8 +83,8 @@ func (s *stage) runHostScript(name string, script types.Script) error {
 
 func (s *stage) runPostScript(sessionResolv, sessionHosts string) error {
 	if s.b.Recipe.BuildData.Post.Script != "" {
-		cmdArgs := []string{"-s", "--build-config", "exec", "--pwd", "/", "--writable"}
-		cmdArgs = append(cmdArgs, "--cleanenv", "--env", aEnvironment, "--env", sEnvironment, "--env", aLabels, "--env", sLabels)
+		cmdArgs := []string{"--build-config", "exec", "--pwd", "/", "--writable"}
+		cmdArgs = append(cmdArgs, "--cleanenv", "--env", aEnvironment, "--env", sEnvironment, "--env", aLabels, "--env", sLabels, "--env", "APPTAINER_MESSAGELEVEL="+sylog.GetEnvVar())
```
Comment (DrDaveD) [inline internal/pkg/build/stage.go:87]: This might be overkill since normally the command line message level setting is passed on to the nested apptainer.  I guess if someone set the environment variable instead of the command line, this would help.  But I'm worried about extraneous INFO messages in the default condition of no messagelevel settings or command line options.  For example what happens if you don't have subuid mapping set up, are there any INFO messages shown again regarding fakeroot?

**Review by DrDaveD — CHANGES_REQUESTED** [review]

File: internal/pkg/runtime/engine/apptainer/container_linux.go (hunk 1 above)
Comment (JasonYangShadow) [reply internal/pkg/runtime/engine/apptainer/container_linux.go]: thanks for the comment, updated.

File: internal/pkg/build/stage.go (hunk 3 above)
Comment (JasonYangShadow) [reply internal/pkg/build/stage.go]: thanks for the good point, yeah, we do not need to pass the env variable as you said. It works as the same as passing the env variable. I also test with `--ignore-subuid` and INFO/WARNING messages are also shown as well. see test
https://github.com/apptainer/apptainer/pull/2556#issue-2574612173

Comment (DrDaveD) [reply internal/pkg/build/stage.go]: Ok, so the INFO message about no subuid does not appear twice.  So I guess it's OK to leave it at the default INFO level instead of dropping it to WARNING by default.

**Review by DrDaveD — CHANGES_REQUESTED** [review]
Now it just needs the rebase for CHANGELOG

**Review by DrDaveD — APPROVED** [review]
