### PR TITLE
Record metadata for original image used from oci

### LINKED ISSUE #2764: Reliable way to reproduce a .sif image
If I build an image file using the `latest` tag, there doesn't appear to be reliable way to discover the version (or ideally the SHA digest) that was used so that it can be reproduced at a later date.

My initial attempt was to use `apptainer inspect` command to get the `org.label-schema.version` label, but this appears to be missing from some images.

### PR DESCRIPTION
**Pull request by afbjorklund**
## Description of the Pull Request (PR):

Add two new fields to the metadata, when building from `docker:`

`org.opencontainers.image.base.name`
`org.opencontainers.image.base.digest`

The fields used for Apptainer are the same that is used in the OCI image specification:

https://github.com/opencontainers/image-spec/blob/main/annotations.md

These record the information that is available, but hidden away:

```console
$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
Digest: sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
Status: Image is up to date for alpine:latest
docker.io/library/alpine:latest
```

In addition to the basic metadata that was previously recorded:

```
org.label-schema.usage.singularity.deffile.bootstrap: docker
org.label-schema.usage.singularity.deffile.from: alpine
```

```
org.opencontainers.image.base.digest: sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
org.opencontainers.image.base.name: docker.io/library/alpine:latest
```

We don't need to record the Id (ConfigFile) or the Manifest checksums:

docker inspect
```
        "Id": "sha256:aded1e1a5b3705116fa0a92ba074a5e0b0031647d9c315983ccba2ee5428ec8b",
        "RepoTags": [
            "alpine:latest"
        ],
        "RepoDigests": [
            "alpine@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c"
        ],
```

podman inspect
```
          "Id": "aded1e1a5b3705116fa0a92ba074a5e0b0031647d9c315983ccba2ee5428ec8b",
          "Digest": "sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c",
          "RepoTags": [
               "docker.io/library/alpine:latest"
          ],
          "RepoDigests": [
               "docker.io/library/alpine@sha256:1c4eef651f65e2f7daee7ee785882ac164b02b78fb74503052a26dc061c90474",
               "docker.io/library/alpine@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c"
          ],
```

But we should record the full name of the image, and the full digest.

https://hub.docker.com/layers/library/alpine/latest/images/sha256-a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c

https://www.redhat.com/en/blog/be-careful-when-pulling-images-short-name

Note: 1c4eef651f65 is the amd64 manifest, that was picked from the image index

```
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 1022,
         "digest": "sha256:1c4eef651f65e2f7daee7ee785882ac164b02b78fb74503052a26dc061c90474",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
```

But we should record the digest that is the same for all platforms.

```
org.label-schema.build-arch: amd64
org.label-schema.build-date: Tuesday_22_April_2025_18:46:13_CEST
```

### This fixes or addresses the following GitHub issues:

 - Fixes #2764

#### Before submitting a PR, make sure you have done the following:

- [x] Read the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] Make sure all commits are signed-off with `git commit -s`, see the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [x] Added changes to the [CHANGELOG](https://github.com/apptainer/apptainer/blob/main/CHANGELOG.md), if necessary according to the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [x] Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md)).
- [x] Based this PR against the appropriate branch according to the [Guidelines for Contributing](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md).
- [x] Added myself as a contributor to the [Contributors File](https://github.com/apptainer/apptainer/blob/main/CONTRIBUTORS.md).

### CODE REVIEW

File: internal/pkg/build/metadata.go [hunk 1]
```diff
@@ -341,6 +341,12 @@ func addBuildLabels(labels map[string]string, b *types.Bundle) error {
 		}
 	}
 
+	// Digest of image
+	if b.Opts.Tag != "" && b.Opts.Digest != "" {
+		labels["org.label-schema.image-tag"] = b.Opts.Tag
+		labels["org.label-schema.image-digest"] = b.Opts.Digest
```
Comment (DrDaveD) [inline internal/pkg/build/metadata.go:347]: Are these label names made up or are they part of some standard?

Comment (afbjorklund) [reply internal/pkg/build/metadata.go:347]: They are made up, or well the "tag" and "digest" is part of the Docker format

Comment (afbjorklund) [reply internal/pkg/build/metadata.go:347]: Note that both words are highly ambiguous, but here they are both clearly defined.

"Tag" is the **full** reference name, and "Digest" is the **full** image digest (with algorithm).

Comment (DrDaveD) [reply internal/pkg/build/metadata.go:347]: I don't think it's OK to make up org.label-schema namespace labels, because those are defined by `org.label-schema`.  It should be allowed to make `org.apptainer` labels.  I see the `org.label-schema` space is now [deprecated](http://label-schema.org/rc1/) and replaced by [`org.opencontainers.image`](https://github.com/opencontainers/image-spec/blob/main/annotations.md).  That says that that namespace MUST NOT be used by extensions.  On the other hand it looks like singularity and apptainer have already added on to `org.label-schema.usage` with sublabels.

Comment (afbjorklund) [reply internal/pkg/build/metadata.go]: I suppose that we could also add `org.opencontainers.image.created` in addition to the old build-date?

But there doesn't seem to exist any field for the full `platform`, I can't even find any reference to build-arch

**Review by DrDaveD — CHANGES_REQUESTED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -23,6 +23,10 @@ For older changes see the [archived Singularity change log](https://github.com/a
   while not using setuid mode.
 - Allow multi-arch oci-archive files that have a nested index with the manifest.
   This is the default format (both for Docker and OCI) when using `nerdctl save`.
+- Record image digest metadata (sha256 from `RepoDigests`), for OCI registry images.
+  Also add the image name (ref) of the image from "docker", with registry and tag.
+  This is useful for traceability, when using `docker.io` or a tag like `latest`.
+  Unfortunately the feature does not work with "docker-archive" or "docker-daemon".
```
[the remark this answers is not in the document]
Comment (afbjorklund) [reply CHANGELOG.md:29]: I will move the changelog to the 1.5.0

[the remark this answers is not in the document]
Comment (afbjorklund) [reply CHANGELOG.md:29]: I thought it would make a nice match with the Dockerfile build log that I added in the other PR

**Review by DrDaveD — APPROVED** [review]
